baseURL: "https://mohitsharma29.github.io/" 
title: Mohit Sharma
theme: PaperMod

# </br> <em>I am looking for internship opportunities in early 2026 and will be on the job market around that time.</em>

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Substack
        #   url: https://mohitsharma17.substack.com/profile/posts
        #   weight: 4 
        - name: Papers
          url: https://scholar.google.com/citations?hl=en&user=m74gCtYAAAAJ&view_op=list_works&sortby=pubdate
          weight: 3
        - name: Research
          url: research/
          weight: 2
        - name: Resources
          url: archive/
          weight: 4
        - name: Blog
          url: blog/
          weight: 5
        - name: Principles
          url: principles/
          weight: 6
        # - name: Data
        #  url: data/
        #  weight: 4 
        # - name: Writing
        #  url: https://mohitsharma17.substack.com/
        #  weight: 6

params:
    description: "This website hosts Mohit Sharma's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Mohit Sharma
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Mohit Sharma
          subtitle: "I am currently a visiting researcher with Prof. Rohit Vaish at IIT Delhi and a Ph.D. candidate at IIIT Delhi, working with Rajiv Ratn and Amit Deshpande (MSR India). I work on learning with imperfect data distributions and care a lot about optimal classification. 
          
          </br></br>

          ### <u>Latest News</u></br></br>

          - **April 2026**: Started as a Visiting Researcher with Prof. [Rohit Vaish](https://rohitvaish.in/) at IIT Delhi.</br>

          - **January 2026**: Starting as a Machine Learning Intern at <b>Tower Research Capital</b>.</br>
          
          - **September 2025**: Our paper <i>On Optimal Steering to Achieve Exact Fairness</i> ([arXiv](https://arxiv.org/abs/2509.15759), [Blog](https://open.substack.com/pub/mohitsharma17/p/seeking-ideal-data-distributions?r=1tjy9l&utm_campaign=post&utm_medium=web&showWelcomeOnShare=true))  has been accepted to <b>Neurips 2025</b>.</br>

          - **April 2025**: Started working as a Research Intern at <b>RIKEN-AIP</b> with Prof. Masashi Sugiyama.
          "
          imageUrl: "img_black_white.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            #- name: Informal CV
            #  url: research/
            - name: Papers
              url: https://scholar.google.com/citations?hl=en&user=m74gCtYAAAAJ&view_op=list_works&sortby=pubdate
            #- name: Data
            #  url: data/
            # - name: Substack
            #   url: https://mohitsharma17.substack.com/profile/posts
            #- name: Tags
            #  url: tags/
            - name: Resources
              url: archive/
            - name: Blog
              url: blog/
            - name: Principles
              url: principles/

    socialIcons:
        - name: CV
          url: https://drive.google.com/file/d/1zZCjLVDKxnmRIYgpVPHm2VwzrIjjT0Fe/view?usp=sharing/
        - name: Email
          url: mailto:mohits@iiitd.ac.in
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=m74gCtYAAAAJ&view_op=list_works&sortby=pubdate
        - name: GitHub
          url: https://github.com/mohitsharma29
        - name: Substack
          url: https://mohitsharma17.substack.com/profile/posts
        #- name: YouTube
        #  url: https://www.youtube.com/@pmichaillat
        - name: Twitter
          url: https://x.com/mohitsharmaj29
        #- name: Bluesky
        #  url: https://bsky.app/profile/pmichaillat.bsky.social
        #- name: Instagram
        #  url: https://www.instagram.com/mohit.sharma_29/
        - name: Goodreads
          url: https://www.goodreads.com/user/show/58133793-mohit-sharma

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Mohit Sharma"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2